language: cpp

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libsdl2-dev libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ocaml-dev libsdl-sge-dev libsdl-ttf2.0-dev libsmpeg-dev

install: make get-deps cmake

script: mkdir build && cd build && cmake ..
