language: cpp

sudo: required

install:
  - cd ..
  - time wget -q http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - time wget -q http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
  - time tar xf SDL2-*.tar.gz
  - time tar xf SDL2_image-*.tar.gz
  - cd SDL2-*
  - ./configure && make && sudo make install
  - cd -
  - cd SDL2_image-*
  - ./configure && make && sudo make install
  - cd -

addons:
  apt:
    packages:
    - libsdl-gfx1.2-dev
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl-ttf2.0-dev
    - libboost-dev
    - cmake
    - make

script: mkdir build && cd build && cmake ..
